//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fairplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int idemp { get; set; }
        public string prenomemp { get; set; }
        public string nomemp { get; set; }
        public string fonction { get; set; }
        public Nullable<int> salaire { get; set; }
        public int idDepartment { get; set; }
    }
}
